# Generated by Django 5.1.3 on 2024-12-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sambandhanewapp', '0003_issuereply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(default='', max_length=100, null=True)),
                ('bookingDate', models.CharField(default='', max_length=100, null=True)),
                ('bookingTime', models.TimeField()),
                ('doctorID', models.CharField(max_length=255)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='sambandhanewapp.useraccount')),
            ],
        ),
    ]
