# Generated by Django 5.1.3 on 2024-12-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('userName', models.CharField(default='', max_length=100, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('docPhoto', models.TextField(default='', null=True)),
                ('userPhoto', models.TextField(default='', null=True)),
                ('character', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('teacher', 'Teacher'), ('student', 'Student'), ('uncle', 'Uncle'), ('brother', 'brother'), ('sister', 'sister')], max_length=100)),
                ('isVerified', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
