# Generated by Django 5.1.3 on 2024-12-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambandhanewapp', '0003_issuereply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('agree', models.IntegerField(default='', null=True)),
                ('disagree', models.IntegerField(default='', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.useraccount')),
                ('issueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.userissue')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('agree', models.IntegerField(default='', null=True)),
                ('disagree', models.IntegerField(default='', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reCommentedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.useraccount')),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.parentcomment')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationName', models.CharField(default='relation', max_length=100)),
                ('issueToken', models.CharField(default='', max_length=100)),
                ('suggestionToken', models.CharField(default='', max_length=255)),
                ('channel', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('issueUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to='sambandhanewapp.useraccount')),
                ('suggestionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to='sambandhanewapp.useraccount')),
            ],
        ),
    ]
