# Generated by Django 5.1.3 on 2024-12-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambandhanewapp', '0004_parentcomment_commentreply_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='character',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('teacher', 'Teacher'), ('student', 'Student'), ('uncle', 'Uncle'), ('sister', 'Sister'), ('brother', 'Brother'), ('daughter', 'Daughter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userissue',
            name='preferredCharacter',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('teacher', 'Teacher'), ('student', 'Student'), ('uncle', 'Uncle'), ('sister', 'Sister'), ('brother', 'Brother'), ('daughter', 'Daughter')], max_length=100),
        ),
    ]
