# Generated by Django 5.1.3 on 2024-12-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambandhanewapp', '0005_alter_useraccount_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reportedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('issue', 'Issue'), ('comment', 'Comment'), ('reply', 'Reply'), ('mitra', 'Mitra')], max_length=100)),
                ('typeID', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reportedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sambandhanewapp.useraccount')),
            ],
        ),
    ]
