# Generated by Django 5.1.3 on 2024-12-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambandhanewapp', '0007_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relationName',
            field=models.CharField(default='relation', max_length=255),
        ),
    ]
