# Generated by Django 5.1.3 on 2024-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sambandhanewapp', '0008_alter_relation_relationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='issueToken',
            field=models.CharField(default='', max_length=255),
        ),
    ]
